Card pokemon
WildCodeSchool-2024-02/JS-lyon-0224-P2-team_rocket pull request #4
Opened 2024-04-10 13:44 UTC by Lith3

2024-04-10 15:03 UTC, AnnesophieMarchet requested changes
ok il y a juste le fichier scss a changer en css

2024-04-10 19:45 UTC, Lith3 commented on client/src/components/PokeCard/PokeCard.scss
Done

2024-04-11 07:46 UTC, AnnesophieMarchet approved these changes
Ok files scss change in css

2024-04-11 07:55 UTC, merged

2024-04-11 07:55 UTC, AnnesophieMarchet commented
PR resolve with Joris, Flakron and Anne-sophie